
all: EasyTransfer

#.SILENT:

.PHONY: EasyTransfer

EasyTransfer:
	make -C EasyTransfer

chxfer:
	make -C EasyTransfer chxfer

clean:
	make -C EasyTransfer clean
	make -C libs/eload clean
	make -C libs/libef3usb clean
