
ifneq ($(shell echo),)
  CMD_EXE := 1
endif

ifdef CMD_EXE

  TARGET := win

  EXE := .exe
  DEL = -del /f $(subst /,\,$1)
  MKDIR = mkdir $(subst /,\,$1)
  RMDIR = -rmdir /s /q $(subst /,\,$1)

else

  EXE :=
  DEL = $(RM) $1
  MKDIR = mkdir $1
  RMDIR = $(RM) -r $1

  UNAME_S := $(shell uname -s)
  ifeq ($(UNAME_S),MINGW32_NT-6.1)
    TARGET := win
  endif
  ifeq ($(UNAME_S),Linux)
    TARGET := linux
  endif
  ifeq ($(UNAME_S),Darwin)
    TARGET := osx
  endif

endif

ifeq ($(TARGET),win)

  CFLAGS+=-DLIBUSB
  CLIBS+=-lusb-1.0
  CFLAGS+=-DWIN32
  CFLAGS+=-DUNICODE
  CFLAGS+=--static

endif

ifeq ($(TARGET),linux)

  CFLAGS+=-DLIBUSB
  CLIBS+=-lusb-1.0
  CFLAGS+=-DPOSIX
  CFLAGS+=-DLINUX

endif

ifeq ($(TARGET),osx)

  CFLAGS+=-DLIBUSB
  CLIBS+=-lusb-1.0
  CFLAGS+=-DPOSIX
  CFLAGS+=-DDARWIN

endif

