
ifneq ($(shell echo),)
  CMD_EXE := 1
endif

TARGET := unknown

ifdef CMD_EXE

  TARGET := win

  EXE := .exe
  DEL = -del /f $(subst /,\,$1)
  MKDIR = mkdir $(subst /,\,$1)
  RMDIR = -rmdir /s /q $(subst /,\,$1)

else

  EXE :=
  DEL = $(RM) $1
  MKDIR = mkdir $1
  RMDIR = $(RM) -r $1

  UNAME_S := $(shell uname -s)
  ifeq ($(UNAME_S),MINGW32_NT-6.1)
    TARGET := win
  endif
  ifeq ($(UNAME_S),Linux)
    TARGET := linux
  endif
  ifeq ($(UNAME_S),Darwin)
    TARGET := osx
  endif

endif

ifeq ($(TARGET),unknown)

  CFLAGS+=-DLIBUSB
  CLIBS+=-lusb-1.0
  CFLAGS+=-DPOSIX

endif

ifeq ($(TARGET),win)

  EXE := .exe
  CFLAGS+=-DLIBUSB
  CLIBS+=-lusb-1.0
  CFLAGS+=-DWIN32
  CFLAGS+=-DUNICODE
# for statically linked build
  CFLAGS+=--static

endif

ifeq ($(TARGET),linux)

  CFLAGS+=-DLIBUSB
  CLIBS+=-lusb-1.0
#  CLIBS+=`libusb-config --libs`
#  CFLAGS+=`pkg-config libusb --cflags`
#  CLIBS+=`pkg-config libusb --libs`
  CFLAGS+=-DPOSIX
  CFLAGS+=-DLINUX
# for statically linked build
#  CFLAGS+=--static
#  CLIBS+=-lpthread -ludev
endif

ifeq ($(TARGET),osx)

  CFLAGS+=-DLIBUSB
  CLIBS+=-lusb-1.0
  CFLAGS+=-DPOSIX
  CFLAGS+=-DDARWIN
# for statically linked build
#  CFLAGS+=--static

endif

